# Generated by Django 5.0.3 on 2024-03-16 15:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('total_score', models.IntegerField(default=0, verbose_name='総得点')),
                ('biography', models.TextField(blank=True, max_length=500, verbose_name='自己紹介')),
                ('twitter_url', models.URLField(blank=True, verbose_name='TwitterURL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHubURL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedInURL')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='国籍')),
                ('occupation', models.CharField(choices=[('Student', '学生'), ('teacher', '教員'), ('SecurityEngineer', 'セキュリティエンジニア'), ('IT', 'IT職'), ('other', 'その他')], max_length=50, verbose_name='職業')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブユーザ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフユーザ')),
                ('is_writer', models.BooleanField(default=False, verbose_name='作問ユーザ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
