# Generated by Django 5.0.3 on 2024-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True, max_length=500, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHubURL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='アクティブユーザ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='スタッフユーザ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_writer',
            field=models.BooleanField(default=False, verbose_name='作問ユーザ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedInURL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(choices=[('Student', '学生'), ('teacher', '教員'), ('SecurityEngineer', 'セキュリティエンジニア'), ('IT', 'IT職'), ('other', 'その他')], max_length=50, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='総得点'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='TwitterURL'),
        ),
    ]
