# Generated by Django 5.0.3 on 2024-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfomationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infomation_category', models.CharField(choices=[('infomation', 'お知らせ'), ('update', 'アップデート'), ('event', 'イベント告知'), ('maintenance', 'メンテナンス'), ('other', 'その他')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
