# Generated by Django 5.0.3 on 2024-03-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', verbose_name='質問')),
                ('answer', models.TextField(default='', verbose_name='回答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Frequently Asked Question',
            },
        ),
        migrations.CreateModel(
            name='InfomationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infomation_category', models.CharField(choices=[('infomation', 'お知らせ'), ('update', 'アップデート'), ('event', 'イベント告知'), ('maintenance', 'メンテナンス'), ('other', 'その他')], max_length=50, verbose_name='カテゴリー')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.CharField(default='admin', max_length=100, verbose_name='投稿者')),
            ],
            options={
                'verbose_name_plural': 'Infomation',
            },
        ),
    ]
