# Generated by Django 5.0.3 on 2024-03-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infomationmodel',
            options={'verbose_name_plural': 'Infomation'},
        ),
    ]
