# Generated by Django 5.0.3 on 2024-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomation', '0002_alter_infomationmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomationmodel',
            name='author',
            field=models.CharField(default='admin', max_length=100, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='infomationmodel',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='infomationmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='infomationmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='infomationmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
