# Generated by Django 5.0.3 on 2024-03-07 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('category_discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_title', models.CharField(max_length=100)),
                ('exercise_discription', models.TextField()),
                ('visiable', models.BooleanField(default=False)),
                ('textbook_url', models.URLField()),
                ('explanation_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_title', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('flag', models.CharField(max_length=100)),
                ('visiable', models.BooleanField(default=False)),
                ('problem', models.TextField()),
                ('hint_one', models.CharField(max_length=200)),
                ('hint_two', models.CharField(max_length=200)),
                ('hint_three', models.CharField(max_length=200)),
                ('cleared_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.categorymodel')),
                ('exercise_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.exercisemodel')),
            ],
        ),
    ]
