# Generated by Django 5.0.3 on 2024-03-16 15:18

import django.db.models.deletion
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=100, verbose_name='カテゴリ名')),
                ('category_discription', models.TextField(blank=True, default='', verbose_name='説明')),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_number', models.IntegerField(default=0, verbose_name='番号')),
                ('exercise_title', models.CharField(default='', max_length=100, verbose_name='タイトル')),
                ('summary', models.TextField(blank=True, default='', verbose_name='概要')),
                ('exercise_discription', mdeditor.fields.MDTextField(default='', verbose_name='説明')),
                ('visible', models.BooleanField(default=False, verbose_name='一般ユーザへの公開')),
                ('textbook', mdeditor.fields.MDTextField(blank=True, verbose_name='教科書')),
                ('explanation', mdeditor.fields.MDTextField(blank=True, verbose_name='解説')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='作成日時')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.categorymodel', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': 'Exercise',
            },
        ),
        migrations.CreateModel(
            name='ChallengeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_number', models.IntegerField(default=0, verbose_name='番号')),
                ('challenge_title', models.CharField(default='', max_length=100, unique=True, verbose_name='タイトル')),
                ('score', models.IntegerField(default='', verbose_name='配点')),
                ('flag', models.CharField(default='', max_length=100, verbose_name='フラグ')),
                ('visible', models.BooleanField(default=False, verbose_name='一般ユーザへの公開')),
                ('is_practice', models.BooleanField(default=False, verbose_name='実戦問題に表示する。')),
                ('discription', mdeditor.fields.MDTextField(default='', verbose_name='説明')),
                ('hint_one', models.CharField(blank=True, default='', max_length=200, verbose_name='ヒントその１')),
                ('hint_two', models.CharField(blank=True, default='', max_length=200, verbose_name='ヒントその２')),
                ('hint_three', models.CharField(blank=True, default='', max_length=200, verbose_name='ヒントその３')),
                ('cleared_count', models.IntegerField(default=0, verbose_name='クリア者数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.categorymodel', verbose_name='カテゴリ')),
                ('exercise_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.exercisemodel', verbose_name='演習名')),
            ],
            options={
                'verbose_name': 'Challenge',
            },
        ),
        migrations.CreateModel(
            name='SubmitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提出日時')),
                ('challenge_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challengemodel', to_field='challenge_title', verbose_name='課題')),
                ('uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid', verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'Submit',
            },
        ),
    ]
