# Generated by Django 5.0.3 on 2024-03-16 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_remove_submitmodel_uuid_submitmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='submitmodel',
            name='uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid', verbose_name='UUID'),
        ),
    ]
