# Generated by Django 5.0.3 on 2024-03-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='教科書URL'),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='解説URL'),
        ),
    ]
