# Generated by Django 5.0.3 on 2024-03-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_exercisemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='explanation_url',
            field=models.URLField(verbose_name='解説URL'),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='textbook_url',
            field=models.URLField(verbose_name='教科書URL'),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='作成日時'),
        ),
    ]
