# Generated by Django 5.0.3 on 2024-03-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_alter_exercisemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemodel',
            name='challenge_number',
            field=models.IntegerField(default=0, verbose_name='番号'),
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='exercise_number',
            field=models.IntegerField(default=0, verbose_name='番号'),
        ),
    ]
