# Generated by Django 5.0.3 on 2024-03-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_challengemodel_challenge_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_discription',
            field=models.TextField(blank=True, default='', verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='hint_one',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ヒントその１'),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='hint_three',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ヒントその３'),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='hint_two',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ヒントその２'),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='explanation_url',
            field=models.URLField(blank=True, verbose_name='解説URL'),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='textbook_url',
            field=models.URLField(blank=True, verbose_name='教科書URL'),
        ),
    ]
