# Generated by Django 5.0.3 on 2024-03-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_alter_categorymodel_category_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.categorymodel', verbose_name='カテゴリ'),
        ),
    ]
