# Generated by Django 5.0.3 on 2024-03-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_exercisemodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengemodel',
            old_name='visiable',
            new_name='visible',
        ),
        migrations.RenameField(
            model_name='exercisemodel',
            old_name='visiable',
            new_name='visible',
        ),
    ]
