# Generated by Django 5.0.3 on 2024-03-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_rename_visiable_challengemodel_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemodel',
            name='is_practice',
            field=models.BooleanField(default=False, verbose_name='実戦問題'),
        ),
    ]
