# Generated by Django 5.0.3 on 2024-03-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_challengemodel_is_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengemodel',
            name='is_practice',
        ),
    ]
