# Generated by Django 5.0.3 on 2024-03-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_remove_challengemodel_is_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemodel',
            name='is_practice',
            field=models.BooleanField(default=False, verbose_name='実戦問題にする。'),
        ),
    ]
