# Generated by Django 5.0.3 on 2024-03-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_alter_challengemodel_exercise_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemodel',
            name='exercise_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.exercisemodel', verbose_name='演習名'),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='is_practice',
            field=models.BooleanField(default=False, verbose_name='実戦問題に表示する。'),
        ),
    ]
