# Generated by Django 5.0.3 on 2024-03-07 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_alter_challengemodel_exercise_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemodel',
            name='challenge_title',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='タイトル'),
        ),
        migrations.CreateModel(
            name='SubmitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提出日時')),
                ('challenge_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challengemodel', to_field='challenge_title', verbose_name='課題')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': 'Submit',
            },
        ),
    ]
