# Generated by Django 5.0.3 on 2024-03-08 14:08

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_alter_challengemodel_challenge_title_submitmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('text_page', models.IntegerField()),
                ('content', mdeditor.fields.MDTextField()),
                ('Exercise_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.exercisemodel', verbose_name='演習名')),
            ],
        ),
    ]
