# Generated by Django 5.0.3 on 2024-03-12 00:53

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0015_textbookmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengemodel',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='exercisemodel',
            name='exercise_discription',
        ),
        migrations.AddField(
            model_name='challengemodel',
            name='discription',
            field=mdeditor.fields.MDTextField(default='', verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='discription',
            field=mdeditor.fields.MDTextField(default='', verbose_name='説明'),
        ),
    ]
