# Generated by Django 5.0.3 on 2024-03-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0017_remove_exercisemodel_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemodel',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='概要'),
        ),
    ]
