# Generated by Django 5.0.3 on 2024-03-16 03:34

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0019_remove_exercisemodel_explanation_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='explanation',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='解説'),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='textbook',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='教科書'),
        ),
    ]
